-- Log générique des appels aux edge functions, pour un rate limiting simple
-- par (fonction, utilisateur) sur une fenêtre glissante. Utilisé par ai-generate
-- (un client pouvait boucler des appels Claude payants avec un system libre)
-- et notify-new-project (un utilisateur authentifié pouvait spammer l'email
-- admin en rappelant la fonction en boucle).
--
-- Aucune policy RLS : table lue/écrite uniquement par les edge functions via
-- la clé service_role, jamais exposée au client (anon/authenticated).

create table if not exists public.edge_function_calls (
  id bigint generated by default as identity primary key,
  fn text not null,
  user_id uuid not null,
  created_at timestamptz not null default now()
);

create index if not exists edge_function_calls_fn_user_created_idx
  on public.edge_function_calls (fn, user_id, created_at desc);

alter table public.edge_function_calls enable row level security;

-- Purge automatique : évite que la table ne grossisse indéfiniment.
create index if not exists edge_function_calls_created_idx
  on public.edge_function_calls (created_at);
